ci: Dynamically parse Hadoop stable test cluster version to download
Previously a hardcoded version was used, which led to the CI breaking
whenever that version was no longer served on the download mirror

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,6 +8,7 @@ addons:
       - libsasl2-dev
       - libsasl2-2
       - check
+      - curl
 
 install:
   # Only install valgrind if we're going to use it
@@ -18,9 +19,13 @@ install:
   # Only download hadoop if we're going to test against the Hadoop CLI MiniCluster
   - |
     if [ "$CK_RUN_SUITE" = "" ] ; then
-      wget http://www.trieuvan.com/apache/hadoop/common/hadoop-3.1.4/hadoop-3.1.4.tar.gz \
-      && tar -xzf hadoop-3.1.4.tar.gz \
-      && sudo mv hadoop-3.1.4 /usr/local/hadoop
+      HADOOP_TGZ=$(curl https://dlcdn.apache.org/hadoop/common/stable/ | sed -nEe 's/.*href="(hadoop-([0-9]+\.){3}tar\.gz)".*/\1/p')
+      if [ -z "$HADOOP_TGZ" ] ; then echo "Unable to fetch stable Hadoop name"; exit 1; fi
+      HADOOP_VER="${HADOOP_TGZ%.tar.gz}"
+      echo "Fetching latest stable Hadoop version $HADOOP_VER"
+      curl -O "https://dlcdn.apache.org/hadoop/common/stable/$HADOOP_TGZ" \
+      && tar xzf "$HADOOP_TGZ" \
+      && sudo mv "$HADOOP_VER" /usr/local/hadoop
     fi
 
 env:
@@ -140,6 +145,9 @@ script:
   - |
     # Only spin up the minicluster if we're testing against it (and if we downloaded it)
     if [ "$CK_RUN_SUITE" = "" ] ; then
+      # There's a bug where the junit jar needs to be explicitly added to the class path for the minicluster to work
+      HADOOP_JUNIT_JAR_PATH=$(find /usr/local/hadoop -name "junit*.jar")
+      export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HADOOP_JUNIT_JAR_PATH}"
       /usr/local/hadoop/bin/mapred minicluster -nomr -format -nnport $HDFS_TEST_NODE_PORT -datanodes 4 &
       CLUSTER_PID=$!
       # Wait until the cluster is up by polling the namenode port with netcat
